### ISSUE TITLE
Will the code be made available?

### ISSUE THREAD

**Issue by morgankohler** [jmaces/rde#1]
Hi I have read this paper and the following using Frank Wolfe and I am hoping to explore it more. Can the code still be made available? I won't mind if it is not totally cleaned up!

**Comment by jmaces** [comment]
Hi, the code for the original RDE paper is now available here. The code for the Frank-Wolfe implementation can be found at [https://github.com/ZIB-IOL/fw-rde](https://github.com/ZIB-IOL/fw-rde)
